name: CI
on:
  push:
    branches: [ master, task4 ]
  pull_request:
    branches: [ master ]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd task4
        mkdir 3rdparty
        mkdir build
        mkdir output
        MAIN_DIR=$(pwd)
        echo ${MAIN_DIR}
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        cd ../build
        cmake -DGOOGLE_TEST_DIR=googletest -DORIGIN=$(pwd) -DCMAKE_INSTALL_PREFIX=${MAIN_DIR}/output ..
        make
        make install
        
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: /home/runner/work/MIPT_Design_Patterns_Assignments/MIPT_Design_Patterns_Assignments/task4/bin/CTestExe
        report-path: /home/runner/work/MIPT_Design_Patterns_Assignments/MIPT_Design_Patterns_Assignments/task4/test-report.tar.gz
        working-directory: /home/runner/work/MIPT_Design_Patterns_Assignments/MIPT_Design_Patterns_Assignments/task4/bin
        
